### ISSUE TITLE
Need Support for Node.js

### ISSUE THREAD

**Issue by invalidred** [Pakhee/Cross-platform-AES-encryption#12]
It will be great to provide support for node.js web services primarily built on express.js framework. Let me know if i could contribute.

**Comment by navneet83** [comment]
Hi @invalidred 
I do not have immediate plan for supporting this, however you are free to extend the code and contribute. I'll work on this as soon as I get some bandwidth!

**Comment by invalidred** [comment]
Hi navneet,

I have started working on Node.js part. Hopefully i should submit a pull request within a week or so. So stay tuned.

**Comment by navneet83** [comment]
Great! keep me posted.
