### ISSUE TITLE
Decryption of file missing last 10 characters from ending

### ISSUE THREAD

**Issue by pablofridman** [Pakhee/Cross-platform-AES-encryption#19]
Before star thanks for the code! very useful. 
I having a problem with big texts, its always cutting the text in some point, I'm not sure if it is cutting the text in the encryption or in the decryption process. 
Thanks!
Pablo

**Comment by muhsindemir** [comment]
in c# library CryptLib.cs
Change Line Number about 120

byte[] plainText = _rcipher.CreateEncryptor().TransformFinalBlock(_enc.GetBytes(_inputText), 0,_inputText.Length);

To

byte[] plainText = _rcipher.CreateEncryptor().TransformFinalBlock(_enc.GetBytes(_inputText), 0, _enc.GetBytes(_inputText).Length);

**Comment by pablofridman** [comment]
Thanks  a lot
