### ISSUE TITLE
Android and C# Encryption & Decryption is not working !

### ISSUE THREAD

**Issue by madhavanadkat** [Pakhee/Cross-platform-AES-encryption#20]
Hello,

As per the code I need to Decrypt the Android Encrypted string in C#  we have the exception called 
"Padding is invalid and cannot be removed."

For android 

            CryptLib _crypt = new CryptLib();
			String output = "";
			String plainText = "Madhav";
			String key = CryptLib.SHA256("Test", 32); // 32 bytes = 256
			String iv = CryptLib.generateRandomIV(16); // 16 bytes = 128 bit
			output = _crypt.encrypt(plainText, key, iv); // encrypt
			System.out.println("encrypted text=" + output);
			

For c# 

            CryptLib _crypt = new CryptLib ();
			String iv = CryptLib.GenerateRandomIV (16); //16 bytes = 128 bits
			string key = CryptLib.getHashSha256("Test", 32); //32 bytes = 256 bits
            Console.WriteLine ("Plain text =" + _crypt.decrypt ("Android Encryption String", key, iv));

"Android Encryption String" = Encrypted string from Android Code , as above.

________________________________________________________________________________

Now i have tried with reverse Like i need to decrypt C# encrypted string in Android , it also give me exception called. 
"javax.crypto.BadPaddingException: EVP_CipherFinal_ex"

For C#

            CryptLib _crypt = new CryptLib ();
			string plainText = "Madhav";
			String iv = CryptLib.GenerateRandomIV (16); //16 bytes = 128 bits
			string key = CryptLib.getHashSha256("Test", 31); //32 bytes = 256 bits
			String cypherText = _crypt.encrypt (plainText, key, iv);
			Console.WriteLine ("iv="+iv);
			Console.WriteLine ("key=" + key);
			Console.WriteLine("Cypher text=" + cypherText);

For android 

            CryptLib _crypt = new CryptLib();
			String output = "";
			String key = CryptLib.SHA256("Test", 32); // 32 bytes = 256
			String iv = CryptLib.generateRandomIV(16); // 16 bytes = 128 bit
			output = _crypt.decrypt("C# Encryption String", key, iv); // decrypt

"C# Encryption String" = Encrypted string from C# Code , as above.
 

Can you please check this if i have done anything wrong , can you please guide me for that , 
that will be appreciable.

Thanks in Advance 
Madhav

**Comment by navneet83** [comment]
You should be using the same IV and the KEY for decryption which you had encryption.
