### ISSUE TITLE
In the example of that I'm not in the same scope of the IV variable value 

### ISSUE THREAD

**Issue by casevictor** [Pakhee/Cross-platform-AES-encryption#21]
How I get the value of the IV? Simple concatenation?
I'm referring about this step -> "Get the encrypted text and the randomIV used for encryption"
Then, I'm very glad if you post an example :+1:

**Comment by navneet83** [comment]
I have provided a method/function to generate ramdom IV. For example in Java, you can see code here https://github.com/Pakhee/Cross-platform-AES-encryption/blob/master/Android/Usage.txt#L8

**Comment by casevictor** [comment]
Yes @navneet83 , thanks for your reply, but I already saw it.
In this example, encrypt/decrypt are in the same context, how I can decrypt in a separate context, where I didn't have the IV value explicit?

**Comment by navneet83** [comment]
You will need IV and the key for decryption.

**Comment by navneet83** [comment]
The initialization vector is XORed against the first plaintext block before encryption in CBC mode, as shown in the https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation  article on block cipher modes. After the first block is decrypted, you still have an intermediate value which has been XORed with the plaintext. Without this, you have little hope of recovering the plaintext.

**Comment by casevictor** [comment]
Uhmm.. then thats my question, how to delivery each random iv, from the client to the server, where the decryption will occurs? You concatenate the string, per example?

**Comment by navneet83** [comment]
Well that totally depends on the way you have implemented your application / software. One option is to create a (web) method which accepts two parameters 1. encrypted text and 2. IV.
