### ISSUE TITLE
I can not find the .h file in your code

### ISSUE THREAD

**Issue by gusheng1987** [Pakhee/Cross-platform-AES-encryption#3]
I wonder where I can find the StringEncryption.h and the NSData+Base64.h,  thank you very much.

**Comment by renatosc** [comment]
Same problem here. Cannot compile because Xcode doesn't find both files. Thanks Michael for the links for the NSData+Base64.

About the StringEncryption.h, he changed the filename to CryptLib but didn't update the code. So, just replace StringEncryption for CryptLib and it should work.

**Comment by navneet83** [comment]
Thank you for reporting these issues. I'll fix these and update the code!

**Comment by navneet83** [comment]
Fixed this one.
