### ISSUE TITLE
Android with C#

### ISSUE THREAD

**Issue by ravenet** [Pakhee/Cross-platform-AES-encryption#4]
Hi,

Thank you for your great lib, I used this with android client and asp.net server,but I am unable to decrypt message in the server. I use the method

 CryptLib.SHA256("16 characters", 32);

when I decrypt in the server, please help me to check.
thanks

**Comment by navneet83** [comment]
This library has been unit tested and works fine. I need to look at your code to help you out. gist ?

**Comment by ravenet** [comment]
Dear Naveen,

I fixed and it is cool
